import type { CameraModel } from "../models";

export const p3CatalogVersion = "user-p3-ir-2026-09-21";
export const p3Entry: Partial<CameraModel> = {
  id: `${p3CatalogVersion}:P3-IR`,
  manufacturer: "User supplied",
  model_name: "P3 · IR 双目",
  display_name: "P3 · IR 双目",
  resolution_width: 2048,
  resolution_height: 1536,
  hfov_deg: 57.31,
  vfov_deg: 44.58,
  focal_length_mm: 4.2,
  min_working_distance_m: 0,
  max_working_distance_m: null,
  stereo: { baseline_mm: 144 },
  housing_mm: [188, 56, 38.5],
  layout_supported: true,
  enabled_for_layout_default: true,
  source: "imported",
  notes:
    "来源：用户于 2026-09-21 提供并确认的 P3 IR 参数；忽略误写的 1.6 MP，按每目 2048×1536 建模。仅纳入 IR 模式。\n双目基线 144 mm；两目按相同内参、平行光轴、沿相机局部水平轴对称分布的理想模型计算，机身位置为两目中心。\n未提供标定外参、畸变、工作距离及图像点定位误差。仿真假设：图像点误差 0.1 px，最小 Marker 4 px，无畸变，距离无硬上限；不代表厂商精度或可达距离。实际深度误差受标定、同步、匹配和光照等影响。\n焦距 4.2±0.21 mm，F2.0，120 fps，400–650 nm / 850 nm 窄带 IR CUT，8 颗 850 nm IR-LED；灯光、曝光、压缩不参与当前几何仿真。",
  catalog: {
    dataset: p3CatalogVersion,
    filename: "用户提供参数 · 2026-09-21",
    camera: {
      model: "P3",
      camera_model_id: "P3",
      sensor: "CMOS 全局快门",
      max_fps_full_resolution: 120,
      transmission: "Marker 数据 / MJPEG 图像压缩",
      power_supply: "POE",
      communication: "千兆以太网",
      interface: "双 RJ45",
      sync: "网络同步",
      standby_power_w: 3.7,
      max_power_w: 15.7,
      weight_g: 484.3,
      dimensions_mm: "188 × 56 × 38.5",
      accuracy_3d_mm: null,
    },
    optical: {
      profile_id: "P3-IR",
      image_mode: "Raw Grayscale / IR",
      source: "用户提供；分辨率已确认，非厂商标定文件",
      environment: "未指定",
      baseline_mm: 144,
      focal_length_mm: 4.2,
      focal_tolerance_mm: 0.21,
      aperture: "F2.0",
      ir_cut: "400–650 nm / 850 nm 窄带 IR CUT",
      ir_led: "8 × 850 nm IR-LED",
      passive_range_m: null,
      active_range_m: null,
      marker_diameter_mm: null,
    },
  },
};
